### ISSUE TITLE
Is DispatchesJob needed?

### ISSUE THREAD

**Issue by alisaleem27** [lorisleiva/request-controller#1]
Firstly, this seems like a really useful little package!

Just want to question the reason behind using the DispatchesJob trait? i don't think its used.

**Comment by lorisleiva** [comment]
Hi there, 👋 

You're right actually. I just blindly went to the base Controller you get on a new application and see what I could use from there but I don't think that would be the responsibility of this package.

I'm making a new commit. 🙂

**Comment by lorisleiva** [comment]
Done and released in `v0.1.1`. 🚀
